import Header from '@/components/header'
import '../styles/globals.css'
import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'
import Footer from '@/components/footer'

const beVietnamPro = Be_Vietnam_Pro({ subsets: ['vietnamese'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
	title: 'Manage',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={beVietnamPro.className}>
				<div className="overflow-x-hidden w-full h-full relative">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	)
}
